add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "tokyonight"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "kamradsmeshnyavy", symbol = " " },
]

[docker_context]
disabled = true

[palettes.tokyonight]
rosewater = "#f7768e"
flamingo  = "#ff9e64"
pink      = "#bb9af7"
mauve     = "#9d7cd8"
red       = "#f7768e"
maroon    = "#db4b4b"
peach     = "#ff9e64"
yellow    = "#e0af68"
green     = "#9ece6a"
teal      = "#73daca"
sky       = "#7dcfff"
sapphire  = "#2ac3de"
blue      = "#7aa2f7"
lavender  = "#c0caf5"
text      = "#c0caf5"
subtext1  = "#a9b1d6"
subtext0  = "#9aa5ce"
overlay2  = "#737aa2"
overlay1  = "#565f89"
overlay0  = "#414868"
surface2  = "#3b4261"
surface1  = "#292e42"
surface0  = "#24283b"
base      = "#1f2335"
mantle    = "#1a1b26"
crust     = "#15161e"