$color = rgba(230,225,207,1.0)
$inner_color = rgba(34,34,34,1.0)
$outer_color = rgba(54,163,217,1.0)
$font_color = rgba(230,225,207,1.0)
$check_color = rgba(184,204,82,1.0)

background {
    monitor =
    path = ~/.config/omarchy/themes/felix/backgrounds/03-Clouds.png
    blur_passes = 0
    blur_size = 8
    color = rgba(0, 0, 0, 0.5)
}
