[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy

[audio]
output = tee name=t ! queue ! autoaudiosink t. ! queue ! audio/x-raw,rate=44100,channels=2,format=S16LE ! filesink location=/tmp/mpd.fifo

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600

[file]
enabled = true
media_dirs = 
    ~/Music/CloudMusic|Cloud Music

[local]
enabled = true
media_dir = ~/Music/CloudMusic

[spotify]
enabled = true
bitrate = 320
volume_normalization = true
