background = #0d0e1a
foreground = #dcd7e6
cursor-color = #f5b7b1

palette = 0=#0d0e1a
palette = 1=#f1948a
palette = 2=#f5b7b1
palette = 3=#f5cba7
palette = 4=#f5b7b1
palette = 5=#c9a0dc
palette = 6=#8dd4cc
palette = 7=#dcd7e6

palette = 8=#4a4d6a
palette = 9=#f1948a
palette = 10=#f5b7b1
palette = 11=#f5cba7
palette = 12=#f5b7b1
palette = 13=#c9a0dc
palette = 14=#8dd4cc
palette = 15=#ffffff
