[colors.primary]
background = "#05080a"
foreground = "#fff6ff"

[colors.cursor]
text = "#05080a"
cursor = "#b2fff3"

[colors.vi_mode_cursor]
text = "#05080a"
cursor = "#b2fff3"

[colors.search.matches]
foreground = "#05080a"
background = "#fff6c3"

[colors.search.focused_match]
foreground = "#05080a"
background = "#ff9fbc"

[colors.footer_bar]
foreground = "#05080a"
background = "#fff6ff"

[colors.selection]
text = "#05080a"
background = "#ffc2df"

[colors.normal]
black = "#05080a"
red = "#ff9fbc"
green = "#baf7b5"
yellow = "#fff6c3"
blue = "#b2fff3"
magenta = "#dfbaff"
cyan = "#ffc79b"
white = "#f3ceff"

[colors.bright]
black = "#4b4c4d"
red = "#ffaecb"
green = "#baf7b5"
yellow = "#fff6c3"
blue = "#b2fff3"
magenta = "#dfbaff"
cyan = "#ffc79b"
white = "#ffe1e1"
