background = #05080a
foreground = #fff6ff
cursor-color = #b2fff3
selection-background = #ffc2df
selection-foreground = #05080a

palette = 0=#05080a
palette = 1=#ff9fbc
palette = 2=#baf7b5
palette = 3=#fff6c3
palette = 4=#b2fff3
palette = 5=#dfbaff
palette = 6=#ffc79b
palette = 7=#f3ceff
palette = 8=#4b4c4d
palette = 9=#ffaecb
palette = 10=#baf7b5
palette = 11=#fff6c3
palette = 12=#b2fff3
palette = 13=#dfbaff
palette = 14=#ffc79b
palette = 15=#ffe1e1
