foreground #e2dff0
background #1a1b2e

selection_foreground            #1a1b2e
selection_background            #a8d8b9

cursor                          #c9b5f5
cursor_text_color               #1a1b2e

url_color                       #89ddff

active_border_color             #a8d8b9
inactive_border_color           #252740
bell_border_color               #f2b5b5
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_foreground           #1a1b2e
active_tab_background           #a8d8b9
inactive_tab_foreground         #6e6a9e
inactive_tab_background         #121326
tab_bar_background              #1a1b2e
tab_bar_margin_color            none

mark1_foreground #1a1b2e
mark1_background #a8d8b9
mark2_foreground #1a1b2e
mark2_background #89ddff
mark3_foreground #1a1b2e
mark3_background #f5bde6

color0 #121326
color8 #6e6a9e

color1 #f2b5b5
color9 #f2b5b5

color2  #a8d8b9
color10 #a8d8b9

color3  #f5e0b5
color11 #f5e0b5

color4  #89ddff
color12 #89ddff

color5  #f5bde6
color13 #f5bde6

color6  #c9b5f5
color14 #c9b5f5

color7  #e2dff0
color15 #ffffff
