# Yazi file picker (xdg-desktop-portal-termfilechooser)
windowrule = float 1, match:class yazi-picker
windowrule = size 800 600, match:class yazi-picker
windowrule = center 1, match:class yazi-picker

# Yazi folder opener (from Chromium "Show in folder", etc)
windowrule = float 1, match:class yazi-folder
windowrule = size 800 600, match:class yazi-folder
windowrule = center 1, match:class yazi-folder



# Быстрый браузер-панель (WaveTerm style)
windowrule = float 1, match:class chrome-google.com__-Default
