$color = rgba(226,223,240,1.0)
$inner_color = rgba(37,39,64,1.0)
$outer_color = rgba(168,216,185,1.0)
$font_color = rgba(226,223,240,1.0)
$check_color = rgba(168,216,185,1.0)

background {
    monitor =
    path = ~/.config/omarchy/themes/cyber-pastel-green/backgrounds/1-gradient.png
    blur_passes = 0
    blur_size = 8
    color = rgba(26,27,46,0.5)
}
