$color = rgba(226,223,240,1.0)
$inner_color = rgba(37,39,64,1.0)
$outer_color = rgba(137,221,255,1.0)
$font_color = rgba(226,223,240,1.0)
$check_color = rgba(137,221,255,1.0)

background {
    monitor =
    path = ~/.config/omarchy/themes/cyber-pastel-cyan/backgrounds/1-grid.png
    blur_passes = 0
    blur_size = 8
    color = rgba(26,27,46,0.5)
}
