# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2

    # Using Omarchy's theme colors (which use standard hex or variables if sourced)
    # Since we use lutgen, we'll let omarchy theme handle borders or just use a nice pastel
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)

    # Change to niri-like side-scrolling layout
    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    rounding = 10
  
    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.1
    dim_special = 0.8

    shadow {
        enabled = true
        range = 3
        render_power = 1
        # color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        xray = true
        ignore_opacity = true
        special = true
        popups = true
    }
}

source = ~/.config/hypr/animations.conf

dwindle {
  preserve_split = true
  special_scale_factor = 0.8
}
