-- General look and feel overrides
hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 4,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 10,
		active_opacity = 0.90,
		inactive_opacity = 0.90,
		fullscreen_opacity = 1.0,
		dim_inactive = true,
		dim_strength = 0.1,
		blur = {
			enabled = true,
			size = 6,
			passes = 3,
			new_optimizations = true,
			xray = true,
			ignore_opacity = true,
			special = true,
			popups = true,
		},
		shadow = {
			enabled = true,
			range = 3,
			render_power = 1,
		},
	},
	dwindle = {
		preserve_split = true,
		special_scale_factor = 0.8,
	},
})

-- Load active animations generated by customizer
local f = io.open(os.getenv("HOME") .. "/dotfiles/apps/hyprland/active_animations.lua", "r")
if f ~= nil then
	io.close(f)
	dofile(os.getenv("HOME") .. "/dotfiles/apps/hyprland/active_animations.lua")
end
