$color = rgba(220,215,230,1.0)
$inner_color = rgba(21,23,38,1.0)
$outer_color = rgba(125,206,160,1.0)
$font_color = rgba(220,215,230,1.0)
$check_color = rgba(125,206,160,1.0)

background {
    monitor =
    path = ~/.config/omarchy/themes/pastel-hacker/backgrounds/1-matrix-rain.png
    blur_passes = 0
    blur_size = 8
    color = rgba(13,14,26,0.6)
}
