$color = rgba(220,215,207,1.0)
$inner_color = rgba(42,44,48,1.0)
$outer_color = rgba(107,184,224,1.0)
$font_color = rgba(220,215,207,1.0)
$check_color = rgba(184,204,128,1.0)

background {
    monitor =
    path = ~/.config/omarchy/themes/felix/backgrounds/03-Clouds.png
    blur_passes = 0
    blur_size = 8
    color = rgba(20, 22, 26, 0.5)
}
