background = #0d0e1a
foreground = #dcd7e6
cursor-color = #8dd4cc

palette = 0=#0d0e1a
palette = 1=#f1948a
palette = 2=#8dd4cc
palette = 3=#f5cba7
palette = 4=#8dd4cc
palette = 5=#c9a0dc
palette = 6=#8dd4cc
palette = 7=#dcd7e6

palette = 8=#4a4d6a
palette = 9=#f1948a
palette = 10=#8dd4cc
palette = 11=#f5cba7
palette = 12=#8dd4cc
palette = 13=#c9a0dc
palette = 14=#8dd4cc
palette = 15=#ffffff
