set -g @om_bg "colour0"
set -g @om_fg "colour7"
set -g @om_red "colour8"
set -g @om_green "colour8"
set -g @om_yellow "colour3"
set -g @om_blue "colour7"
set -g @om_magenta "colour7"
set -g @om_cyan "colour3"
set -g @om_white "colour7"
set -g @om_black "colour0"
set -g @om_overlay_0 "colour8"
set -g @om_overlay1 "colour7"
set -g @om_rosewater "colour7"
set -g @om_lavender "colour7"
set -g @om_maroon "colour8"
