#!/bin/bash
# Toggle between top and bottom shell layouts

SHELL_DIR="$HOME/.config/omarchy"
CURRENT=$(cat "$SHELL_DIR/shell.json" | grep '"position": "top"')

if [ -z "$CURRENT" ]; then
    # It's currently bottom, switch to top
    cp "$SHELL_DIR/shell-top.json" "$SHELL_DIR/shell.json"
    notify-send -t 1000 "Omarchy Shell" "Layout: Top"
else
    # It's currently top, switch to bottom
    cp "$SHELL_DIR/shell-bottom.json" "$SHELL_DIR/shell.json"
    notify-send -t 1000 "Omarchy Shell" "Layout: Bottom"
fi

omarchy restart shell
